name: Build, test and publish tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and test with Gradle
      run: ./gradlew build
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1.9
      if: always()
      with:
        files: build/test-results/**/*.xml
